# Generated by Django 2.1.5 on 2019-03-13 18:35

import MAIN.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('logo', models.ImageField(upload_to=MAIN.models.project_logo_upload_path)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('kind', models.CharField(choices=[('OTHER', 'Other'), ('BUG', 'Bug'), ('FEATURE', 'Feature')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('TO-DO', 'To do'), ('IN-PROGRESS', 'In progress'), ('DONE', 'Task done'), ('TEST', 'In testing'), ('CLOSED', 'Closed'), ('SUSPENDED', 'Suspended')], default='TO-DO', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal priority'), ('HIGH', 'High priority'), ('URGENT', 'Urgent priority'), ('LOW', 'Low priority')], default='NORMAL', max_length=20)),
                ('estimation', models.DecimalField(decimal_places=1, default=0, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='MAIN.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now=True)),
                ('commentator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='MAIN.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=MAIN.models.task_file_upload_path)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_files', to='MAIN.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=1, default=0, max_digits=5, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_time_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
