# Generated by Django 2.1.5 on 2019-05-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_auto_20190316_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_set', to='MAIN.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO-DO', 'To do'), ('IN-PROGRESS', 'In progress'), ('DONE', 'Task done'), ('CLOSED', 'Closed')], default='TO-DO', max_length=20),
        ),
    ]
